"""Microsoft GraphRAG behind the StructuredMemoryBackend boundary.

All interaction goes through the versioned ``graphrag`` CLI (index/query)
plus reads of its parquet output. Nothing here imports graphrag internals,
so a package upgrade, a different implementation, or a purpose-built graph
can replace this module without touching callers.

Derived state is disposable and rebuildable; the source corpus is
authoritative. Index outputs live under the configured project root, which
is git-ignored work state — only manifests, exported snapshots, and run
records are committed.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import time
import tempfile
from pathlib import Path

import pandas as pd
from graph_memory.graphrag_backend.process import run_bounded

SOLUTION_ROOT = Path(__file__).resolve().parent.parent.parent
if str(SOLUTION_ROOT) not in sys.path:
    sys.path.insert(0, str(SOLUTION_ROOT))

from graph_memory.config import GraphMemoryConfig  # noqa: E402
from graph_memory.graphrag_backend.backend import (  # noqa: E402
    QUERY_MODES,
    GraphClaim,
    GraphCommunity,
    GraphEntity,
    GraphQueryResult,
    GraphRelationship,
    GraphSnapshot,
    IndexReport,
)
from graph_memory.sources.adapters import (  # noqa: E402
    adapt_corpus,
    write_input_docs,
)

SETTINGS_TEMPLATE = """\
### Generated by graph_memory for book Chapter 4. Do not hand-edit:
### rebuild via MicrosoftGraphRAGBackend.write_settings().
### LLM settings ###

completion_models:
  default_completion_model:
    model_provider: {chat_provider}
    model: {chat_model}
    api_base: {ollama_host}
    api_key: ollama
    auth_method: api_key
    retry:
      type: exponential_backoff

embedding_models:
  default_embedding_model:
    model_provider: {embedding_provider}
    model: {embedding_model}
    api_base: {ollama_host}
    api_key: ollama
    retry:
      type: exponential_backoff

### Document processing settings ###

input:
  type: text

chunking:
  type: tokens
  size: {chunk_size}
  overlap: {chunk_overlap}
  encoding_model: o200k_base

### Storage settings ###

input_storage:
  type: file
  base_dir: "input"

output_storage:
  type: file
  base_dir: "output"

reporting:
  type: file
  base_dir: "logs"

cache:
  type: json
  storage:
    type: file
    base_dir: "cache"

vector_store:
  type: lancedb
  db_uri: output\\lancedb

### Workflow settings ###

embed_text:
  embedding_model_id: default_embedding_model

extract_graph:
  completion_model_id: default_completion_model
  prompt: "prompts/extract_graph.txt"
  entity_types: [{entity_types}]
  max_gleanings: {max_gleanings}

summarize_descriptions:
  completion_model_id: default_completion_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: {claim_extraction}
  completion_model_id: default_completion_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: {max_gleanings}

community_reports:
  completion_model_id: default_completion_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

snapshots:
  graphml: false
  embeddings: false

### Query settings ###

local_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  completion_model_id: default_completion_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_search_reduce_prompt.txt"

basic_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"
"""


def _as_list(value) -> list[str]:
    """Coerce GraphRAG id fields to string lists.

    Parquet columns arrive as lists, numpy arrays, scalars, or nulls
    depending on the table. Anything unrecognised degrades to [] so a
    schema variation can only cause counted orphans, never crashes.
    """
    if value is None:
        return []
    try:
        import pandas as pd

        if value is pd.NA or (isinstance(value, float) and pd.isna(value)):
            return []
    except ImportError:
        pass
    if isinstance(value, str):
        text = value.strip()
        if text.startswith("[") and text.endswith("]"):
            inner = text[1:-1].strip()
            return (
                [p.strip() for p in inner.split(",") if p.strip()]
                if inner
                else []
            )
        return [p.strip() for p in text.split(",") if p.strip()]
    if isinstance(value, (list, tuple)):
        return [str(v) for v in value]
    # numpy arrays and other sequences: iterate, never str() the container.
    if hasattr(value, "__iter__"):
        try:
            return [str(v) for v in value]
        except TypeError:
            return []
    return [str(value)]


class MicrosoftGraphRAGBackend:
    """GraphRAG CLI driver implementing StructuredMemoryBackend."""

    def __init__(self, config: GraphMemoryConfig) -> None:
        self.config = config
        self.root = SOLUTION_ROOT / config.project_root
        self.exe = (
            Path(config.graphrag_executable)
            if Path(config.graphrag_executable).is_absolute()
            else SOLUTION_ROOT / config.graphrag_executable
        )

    # -- setup ----------------------------------------------------------

    def corpus_root(self) -> Path:
        return SOLUTION_ROOT / self.config.source_root

    def corpus_hash(self) -> str:
        digest = hashlib.sha1()
        for artifact in adapt_corpus(self.corpus_root()):
            digest.update(artifact.artifact_id.encode())
            digest.update(artifact.content_hash.encode())
        return digest.hexdigest()[:16]

    def write_settings(self) -> Path:
        self.root.mkdir(parents=True, exist_ok=True)
        settings = SETTINGS_TEMPLATE.format(
            chat_provider=self.config.chat_provider,
            chat_model=self.config.chat_model,
            embedding_provider=self.config.embedding_provider,
            embedding_model=self.config.embedding_model,
            ollama_host=self.config.ollama_host,
            chunk_size=self.config.gr_chunk_size,
            chunk_overlap=self.config.gr_chunk_overlap,
            entity_types=",".join(self.config.entity_types),
            max_gleanings=self.config.max_gleanings,
            claim_extraction=str(self.config.claim_extraction).lower(),
        )
        path = self.root / "settings.yaml"
        path.write_text(settings, encoding="utf-8")
        return path

    def prepare_input(self) -> dict:
        """Adapt the canonical corpus into GraphRAG input documents."""
        artifacts = adapt_corpus(self.corpus_root())
        manifest = write_input_docs(artifacts, self.root / "input")
        return {
            "artifacts": len(artifacts),
            "manifest": manifest,
            "corpus_hash": self.corpus_hash(),
        }

    # -- indexing --------------------------------------------------------

    def index(self, force: bool = False) -> IndexReport:
        """Run the full GraphRAG indexing pipeline via CLI."""
        if (self.root / "output").exists() or (self.root / "index_manifest.json").exists():
            raise FileExistsError("Choose a new MEMORY_GRAPH_ROOT for a new index version")
        self.root.mkdir(parents=True, exist_ok=True)
        if not (self.root / "prompts").exists():
            init = run_bounded([str(self.exe), "init", "--root", str(self.root)],
                               cwd=str(SOLUTION_ROOT), timeout=120)
            if init.returncode:
                raise RuntimeError(init.stderr[-2000:])
        self.write_settings()
        prep = self.prepare_input()
        (self.root / "input_manifest.json").write_text(
            json.dumps(prep["manifest"], indent=2), encoding="utf-8")
        frozen = self.config.stamped(self.config.code_commit).to_dict()
        frozen.update(corpus_hash=prep["corpus_hash"], status="building",
            input_hashes={p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                          for p in (self.root / "input").glob("*") if p.is_file()},
            settings_sha256=hashlib.sha256((self.root / "settings.yaml").read_bytes()).hexdigest(),
            prompt_hashes={p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                           for p in (self.root / "prompts").glob("*") if p.is_file()})
        manifest_path = self.root / "index_manifest.json"
        manifest_path.write_text(json.dumps(frozen, indent=2), encoding="utf-8")
        output_dir = self.root / "output"
        started = time.perf_counter()
        try:
            proc = run_bounded([str(self.exe), "index", "--root", str(self.root)],
                cwd=str(SOLUTION_ROOT), timeout=self.config.index_timeout_seconds)
        except BaseException as exc:
            frozen.update(status="failed", error=type(exc).__name__)
            manifest_path.write_text(json.dumps(frozen, indent=2), encoding="utf-8")
            raise
        wall = time.perf_counter() - started
        (self.root / "logs" / "index_stdout.txt").parent.mkdir(
            parents=True, exist_ok=True
        )
        (self.root / "logs" / "index_stdout.txt").write_text(
            proc.stdout[-200000:], encoding="utf-8"
        )
        (self.root / "logs" / "index_stderr.txt").write_text(
            proc.stderr[-200000:], encoding="utf-8"
        )
        report = IndexReport(
            output_dir=str(output_dir),
            corpus_version=self.config.corpus_version,
            corpus_hash=prep["corpus_hash"],
            graphrag_version=self.config.graphrag_version,
            chat_model=f"{self.config.chat_provider}/{self.config.chat_model}",
            embedding_model=(
                f"{self.config.embedding_provider}/"
                f"{self.config.embedding_model}"
            ),
            wall_seconds=round(wall, 1),
        )
        if proc.returncode != 0:
            report.failures.append(
                f"graphrag index exited {proc.returncode}: "
                f"{proc.stderr[-2000:]}"
            )
        try:
            snapshot = self.snapshot()
            report.entities = len(snapshot.entities)
            report.relationships = len(snapshot.relationships)
            report.claims = len(snapshot.claims)
            report.communities = len(snapshot.communities)
            report.community_reports = sum(
                1 for c in snapshot.communities if c.summary
            )
            report.text_units = snapshot.text_units
            report.documents = snapshot.documents
        except Exception as exc:  # keep the report even if parsing fails
            report.failures.append(f"snapshot parse failed: {exc}")
        if report.community_reports < report.communities:
            report.failures.append("one or more community reports missing")
        frozen.update(status="complete" if not report.failures else "degraded",
                      output_hashes=self.output_hashes())
        manifest_path.write_text(json.dumps(frozen, indent=2), encoding="utf-8")
        (self.root / "index_report.json").write_text(
            json.dumps(report.to_dict(), indent=2), encoding="utf-8")
        return report

    # -- output tables ---------------------------------------------------

    def _output_dir(self) -> Path:
        return self.root / "output"

    def _read_table(self, name: str) -> pd.DataFrame:
        matches = sorted(self._output_dir().glob(f"{name}.parquet"))
        if not matches:
            raise FileNotFoundError(f"no {name}.parquet under {self._output_dir()}")
        return pd.read_parquet(matches[-1])

    def snapshot(self) -> GraphSnapshot:
        entities = [
            GraphEntity(
                entity_id=str(row.get("id", row.get("human_readable_id", ""))),
                name=str(row.get("title", "")),
                kind=str(row.get("type", "")),
                description=str(row.get("description", "") or ""),
                source_text_units=_as_list(row.get("text_unit_ids")),
                degree=int(row.get("degree", 0) or 0),
            )
            for _, row in self._read_table("entities").iterrows()
        ]
        relationships = [
            GraphRelationship(
                relationship_id=str(row.get("id", "")),
                source=str(row.get("source", "")),
                target=str(row.get("target", "")),
                description=str(row.get("description", "") or ""),
                weight=float(row.get("weight", 0.0) or 0.0),
                source_text_units=_as_list(row.get("text_unit_ids")),
            )
            for _, row in self._read_table("relationships").iterrows()
        ]
        claims: list[GraphClaim] = []
        try:
            claim_rows = self._read_table("covariates")
            # v3 covariates carry a singular text_unit_id; older shapes
            # carry a text_unit_ids list. Accept both, orphans otherwise.
            unit_col = (
                "text_unit_id"
                if "text_unit_id" in claim_rows.columns
                else "text_unit_ids"
            )
            for _, row in claim_rows.iterrows():
                raw_units = row.get(unit_col)
                if isinstance(raw_units, str):
                    units = [raw_units] if raw_units else []
                else:
                    units = _as_list(raw_units)
                claims.append(
                    GraphClaim(
                        claim_id=str(row.get("id", "")),
                        subject=str(row.get("subject_id", "") or "")[:160],
                        description=str(row.get("description", "") or ""),
                        claim_type=str(
                            row.get("covariate_type", row.get("type", ""))
                            or ""
                        ),
                        status=str(row.get("status", "") or ""),
                        source_text_units=units,
                    )
                )
        except FileNotFoundError:
            pass
        communities: list[GraphCommunity] = []
        # Summaries live in the community_reports table, keyed by community
        # id; the communities table carries membership. A community with no
        # report row (e.g. a failed extraction) keeps an empty summary so
        # the gap stays visible instead of vanishing.
        report_summaries: dict[str, str] = {}
        try:
            for _, row in self._read_table("community_reports").iterrows():
                key = str(row.get("community", ""))
                if key:
                    report_summaries[key] = str(row.get("summary", "") or "")
        except FileNotFoundError:
            pass
        try:
            for _, row in self._read_table("communities").iterrows():
                community_id = str(row.get("community", row.get("id", "")))
                communities.append(
                    GraphCommunity(
                        community_id=community_id,
                        title=str(row.get("title", "") or ""),
                        summary=report_summaries.get(community_id, ""),
                        level=int(row.get("level", 0) or 0),
                        size=int(row.get("size", 0) or 0),
                        source_text_units=_as_list(row.get("text_unit_ids")),
                    )
                )
        except FileNotFoundError:
            pass
        try:
            text_units = len(self._read_table("text_units"))
        except FileNotFoundError:
            text_units = 0
        try:
            documents = len(self._read_table("documents"))
        except FileNotFoundError:
            documents = 0
        return GraphSnapshot(
            entities=entities,
            relationships=relationships,
            claims=claims,
            communities=communities,
            text_units=text_units,
            documents=documents,
        )

    def text_unit_sources(self) -> dict[str, list[str]]:
        """Map text_unit_id -> document titles (filenames).

        Joins through the documents table (id -> title): text units carry
        document *ids*, and in small corpora a document and its sole text
        unit may even share one id. The documents table also carries the
        reverse text_unit_ids list, consulted as a fallback. A schema
        variation degrades to partial mapping, never to silent orphans.
        """
        titles: dict[str, str] = {}
        reverse: dict[str, list[str]] = {}
        try:
            documents = self._read_table("documents")
            for _, row in documents.iterrows():
                doc_id = str(row.get("id", "") or "")
                title = str(row.get("title", "") or "")
                if doc_id and title:
                    titles[doc_id] = title
                for unit in _as_list(row.get("text_unit_ids")):
                    if unit and title and title not in reverse.get(unit, []):
                        reverse.setdefault(unit, []).append(title)
        except FileNotFoundError:
            pass
        mapping: dict[str, list[str]] = {}
        try:
            units = self._read_table("text_units")
        except FileNotFoundError:
            return {k: list(v) for k, v in reverse.items()}
        unit_col = (
            "document_ids" if "document_ids" in units.columns else "document_id"
        )
        for _, row in units.iterrows():
            unit_id = str(row.get("id", "") or "")
            if not unit_id:
                continue
            raw = row.get(unit_col)
            doc_ids = _as_list(raw) if raw is not None else []
            docs = [titles[d] for d in doc_ids if d in titles]
            docs.extend(d for d in reverse.get(unit_id, []) if d not in docs)
            if docs:
                mapping[unit_id] = docs
        return mapping

    # -- queries ----------------------------------------------------------

    def query(self, question: str, mode: str) -> GraphQueryResult:
        if mode not in QUERY_MODES:
            raise ValueError(f"unknown query mode: {mode}")
        started = time.perf_counter()
        with tempfile.TemporaryDirectory(prefix="memory-graph-query-") as tmp:
            output = Path(tmp) / "result.json"
            python = self.exe.with_name("python.exe" if sys.platform == "win32" else "python")
            worker = Path(__file__).with_name("query_worker.py")
            proc = run_bounded([str(python), str(worker), "--root", str(self.root),
                                "--mode", mode, "--question", question,
                                "--level", str(self.config.community_level),
                                "--version", self.config.graphrag_version,
                                "--output", str(output)], cwd=str(SOLUTION_ROOT),
                               timeout=self.config.query_timeout_seconds)
            if proc.returncode != 0 or not output.exists():
                raise RuntimeError(f"GraphRAG {mode} failed ({proc.returncode}): {proc.stderr[-4000:]}")
            payload = json.loads(output.read_text(encoding="utf-8"))
        wall = time.perf_counter() - started
        answer = payload["answer"]
        if not isinstance(answer, str):
            answer = json.dumps(answer, ensure_ascii=False)
        context = payload["context"]
        if not isinstance(context, dict):
            context = {"returned_context": context}
        return GraphQueryResult(
            question=question,
            method=mode,
            answer_text=answer,
            wall_seconds=round(wall, 1),
            latency_ms=round(wall * 1000.0, 1),
            context_tokens_estimate=max(1, len(json.dumps(context)) // 4),
            raw_output=proc.stdout[-20000:],
            context_data=context,
            source_artifacts=self.context_sources(context),
        )

    def context_sources(self, context: dict) -> list[str]:
        """Resolve actual context rows to lineage candidates, not support verdicts."""
        units: set[str] = set()
        categories = {"sources": "text_units", "entities": "entities",
                      "relationships": "relationships", "claims": "covariates",
                      "reports": "communities"}
        for category, table in categories.items():
            rows = context.get(category, [])
            if not isinstance(rows, list):
                continue
            try:
                frame = self._read_table(table)
            except FileNotFoundError:
                continue
            for selected in rows:
                if not isinstance(selected, dict):
                    continue
                selected_id = str(selected.get("id", ""))
                for _, row in frame.iterrows():
                    identities = {str(row.get("id", "")), str(row.get("human_readable_id", ""))}
                    if table == "communities":
                        identities.add(str(row.get("community", "")))
                    if not selected_id or selected_id not in identities:
                        continue
                    if table == "text_units":
                        units.add(str(row["id"]))
                    else:
                        units.update(_as_list(row.get("text_unit_ids", row.get("text_unit_id"))))
        manifest_path = self.root / "input_manifest.json"
        if manifest_path.exists():
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        else:
            from graph_memory.health.checks import _input_manifest
            manifest = _input_manifest(self)
        mapping = self.text_unit_sources()
        return sorted({manifest[doc] for unit in units for doc in mapping.get(unit, []) if doc in manifest})

    def output_hashes(self) -> dict[str, str]:
        return {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                for p in sorted(self._output_dir().glob("*.parquet"))}

    def query_basic(self, question: str) -> GraphQueryResult:
        return self.query(question, "basic")

    def query_local(self, question: str) -> GraphQueryResult:
        return self.query(question, "local")

    def query_global(self, question: str) -> GraphQueryResult:
        return self.query(question, "global")

    def query_drift(self, question: str) -> GraphQueryResult:
        return self.query(question, "drift")

    # -- version record ----------------------------------------------------

    def manifest(self) -> dict:
        frozen_path = self.root / "index_manifest.json"
        if frozen_path.exists():
            frozen = json.loads(frozen_path.read_text(encoding="utf-8"))
            return {**frozen, "current_corpus_hash": self.corpus_hash(),
                    "current_output_hashes": self.output_hashes()}
        settings_path = self.root / "settings.yaml"
        prompts: dict[str, str] = {}
        prompts_dir = self.root / "prompts"
        if prompts_dir.is_dir():
            for prompt_file in sorted(prompts_dir.glob("*.txt")):
                content = prompt_file.read_text(encoding="utf-8")
                prompts[prompt_file.name] = hashlib.sha1(
                    content.encode()
                ).hexdigest()[:12]
        return {
            "graphrag_version": self.config.graphrag_version,
            "chat_model": (
                f"{self.config.chat_provider}/{self.config.chat_model}"
            ),
            "embedding_model": (
                f"{self.config.embedding_provider}/"
                f"{self.config.embedding_model}"
            ),
            "entity_types": list(self.config.entity_types),
            "claim_extraction": self.config.claim_extraction,
            "max_gleanings": self.config.max_gleanings,
            "gr_chunking": {
                "size": self.config.gr_chunk_size,
                "overlap": self.config.gr_chunk_overlap,
            },
            "community_level": self.config.community_level,
            "corpus_version": self.config.corpus_version,
            "corpus_hash": self.corpus_hash(),
            "index_timestamp": self.config.index_timestamp,
            "code_commit": self.config.code_commit,
            "settings_sha1": (
                hashlib.sha1(
                    settings_path.read_bytes()
                ).hexdigest()[:16]
                if settings_path.exists()
                else None
            ),
            "prompt_hashes": prompts,
            "config": self.config.to_dict(),
            "lineage_status": "observed-legacy-index" if self._output_dir().exists() else "new-build",
            "output_hashes": self.output_hashes(),
        }
